# Generated by Django 2.2 on 2019-08-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0059_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DopMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
            ],
            options={
                'db_table': '_dop_money',
            },
        ),
        migrations.CreateModel(
            name='DopTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_summ', models.IntegerField()),
                ('max_summ', models.IntegerField()),
            ],
            options={
                'db_table': '_dop_types',
            },
        ),
        migrations.CreateModel(
            name='MoneyReceivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Объекты списания')),
            ],
            options={
                'db_table': '_money_receivers',
            },
        ),
        migrations.RemoveField(
            model_name='dop_money',
            name='dop_type',
        ),
        migrations.RemoveField(
            model_name='dop_money',
            name='nak_id',
        ),
        migrations.DeleteModel(
            name='Money_receivers',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='codes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lastcost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='money',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moneys',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nakl_for_zagot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nakl_money_other',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nakl_money_zakup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pizzerias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postavsh',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rashod_zagot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receivers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='types_of_money',
            options={},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zagot_types',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zakupshiki',
            options={},
        ),
        migrations.AlterModelManagers(
            name='pizzerias',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='units',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='kolvo',
            field=models.FloatField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='shtrih',
            field=models.CharField(max_length=50, verbose_name='Штрих-код'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='kolvo',
            field=models.FloatField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='ingredients_dop_info',
            name='procent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredients_dop_info',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', unique=True),
        ),
        migrations.AlterField(
            model_name='ingredients_dop_info',
            name='srok',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lastcost',
            name='cost',
            field=models.FloatField(verbose_name='Последняя цена'),
        ),
        migrations.AlterField(
            model_name='lastcost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Products'),
        ),
        migrations.AlterField(
            model_name='money',
            name='dat',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='dsumma',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='is_calculated',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='isumma',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='nak_id',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='money',
            name='nsumma',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='psumma',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='rsumma',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='vsumma',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moneys',
            name='kolvo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='moneys',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Types_of_money', unique=True),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='ac_kolvo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='in_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='is_accepted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='is_maked',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='is_returned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='nak_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Products'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='pkolvo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='shtrih',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='srok',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='summ',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='tkolvo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Zagot_types'),
        ),
        migrations.AlterField(
            model_name='nakl_money_other',
            name='for_why',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nakl_money_other',
            name='kolvo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nakl_money_other',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nakl_money_other',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Types_of_money'),
        ),
        migrations.AlterField(
            model_name='nakl_money_zakup',
            name='kolvo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nakl_money_zakup',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nakl_money_zakup',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Types_of_money'),
        ),
        migrations.AlterField(
            model_name='pizzerias',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postavsh',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postavsh',
            name='firm_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postavsh',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='postavsh',
            name='place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='artikul',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='edizm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Units', verbose_name='Ед.измерения'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=100, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='maks_zakup',
            field=models.IntegerField(verbose_name='Закупка на дни'),
        ),
        migrations.AlterField(
            model_name='products',
            name='min_zakup',
            field=models.IntegerField(verbose_name='Минимальные дни для закупки'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prigot',
            field=models.BooleanField(verbose_name='Приготовляемый товар?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rashod',
            field=models.FloatField(verbose_name='Расход в день'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата накладной'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='fact_kol',
            field=models.FloatField(verbose_name='Фактическое кол-во'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_accepted',
            field=models.BooleanField(verbose_name='Накладная принята?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_accepted_zakup',
            field=models.BooleanField(verbose_name='Принято закупщиком?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_delivered',
            field=models.BooleanField(verbose_name='Куплен?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_returned',
            field=models.BooleanField(verbose_name='Возвращен?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='min_srok',
            field=models.DateField(blank=True, null=True, verbose_name='Минимальный срок годности'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='nak_id',
            field=models.CharField(max_length=50, verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Products', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='new_cost',
            field=models.FloatField(verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__role': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Закупщик'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_kol',
            field=models.FloatField(verbose_name='Купленное кол-во'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='srok',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='summ',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='rashod_zagot',
            name='kol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rashod_zagot',
            name='nak_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Nakl_for_zagot'),
        ),
        migrations.AlterField(
            model_name='rashod_zagot',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Products'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.Pizzerias', verbose_name='Пиццерия'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='salers',
            name='last_cost',
            field=models.FloatField(verbose_name='Последняя цена'),
        ),
        migrations.AlterField(
            model_name='salers',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='spis',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='spis',
            name='kol',
            field=models.FloatField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='spis',
            name='nak_id',
            field=models.IntegerField(verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='spis',
            name='product',
            field=models.CharField(max_length=100, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='spis',
            name='user',
            field=models.CharField(max_length=20, verbose_name='Кем выдано'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Products', unique=True, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ostat',
            field=models.FloatField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='types_of_money',
            name='types',
            field=models.CharField(max_length=50, unique=True, verbose_name='Типы'),
        ),
        migrations.AlterField(
            model_name='units',
            name='edizm',
            field=models.CharField(max_length=20, verbose_name='Ед.измерения'),
        ),
        migrations.AlterField(
            model_name='zagot_types',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Products'),
        ),
        migrations.AlterField(
            model_name='zagot_types',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zakupshiki',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', unique=True, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='zakupshiki',
            name='user',
            field=models.ForeignKey(limit_choices_to={'roles__role': 3}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Закупщик'),
        ),
        migrations.AlterModelTable(
            name='categories',
            table='_categories',
        ),
        migrations.AlterModelTable(
            name='codes',
            table='_codes',
        ),
        migrations.AlterModelTable(
            name='consuption',
            table='_consuption',
        ),
        migrations.AlterModelTable(
            name='ingredients',
            table='_ingredients',
        ),
        migrations.AlterModelTable(
            name='ingredients_dop_info',
            table='_ingredients_dop_info',
        ),
        migrations.AlterModelTable(
            name='lastcost',
            table='_lastcost',
        ),
        migrations.AlterModelTable(
            name='money',
            table='_money',
        ),
        migrations.AlterModelTable(
            name='moneys',
            table='_moneys',
        ),
        migrations.AlterModelTable(
            name='nakl_for_zagot',
            table='_nakl_for_zagot',
        ),
        migrations.AlterModelTable(
            name='nakl_money_other',
            table='_nakl_money_other',
        ),
        migrations.AlterModelTable(
            name='nakl_money_zakup',
            table='_nakl_money_zakup',
        ),
        migrations.AlterModelTable(
            name='pizzerias',
            table='_pizzerias',
        ),
        migrations.AlterModelTable(
            name='postavsh',
            table='_postavsh',
        ),
        migrations.AlterModelTable(
            name='products',
            table='_products',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='_purchase',
        ),
        migrations.AlterModelTable(
            name='rashod_zagot',
            table='_rashod_zagot',
        ),
        migrations.AlterModelTable(
            name='receivers',
            table='_receivers',
        ),
        migrations.AlterModelTable(
            name='salers',
            table='_salers',
        ),
        migrations.AlterModelTable(
            name='spis',
            table='_spis',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='_stock',
        ),
        migrations.AlterModelTable(
            name='types_of_money',
            table='_types_of_money',
        ),
        migrations.AlterModelTable(
            name='units',
            table='_units',
        ),
        migrations.AlterModelTable(
            name='zagot_types',
            table='_zagot_types',
        ),
        migrations.AlterModelTable(
            name='zakupshiki',
            table='_zakupshiki',
        ),
        migrations.DeleteModel(
            name='Dop_money',
        ),
        migrations.DeleteModel(
            name='Dop_types',
        ),
        migrations.AddField(
            model_name='dopmoney',
            name='dop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.DopTypes'),
        ),
        migrations.AddField(
            model_name='dopmoney',
            name='nak_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Purchase'),
        ),
    ]
