# Generated by Django 2.2 on 2019-08-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0067_purchase_saler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Заказан?'),
        ),
    ]
