# Generated by Django 2.2 on 2019-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='kolvo',
            field=models.FloatField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='scena',
            field=models.FloatField(default=1, verbose_name='Ср.цена'),
        ),
    ]
