# Generated by Django 2.1.3 on 2019-03-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Завсклад'), (2, 'Кассир'), (3, 'Закупщик'), (4, 'Заготовщик'), (5, 'Пиццемейкер'), (6, 'Пиццедоставщик'), (7, 'Пиццекассир')], verbose_name='Роль'),
        ),
    ]
