# Generated by Django 2.2 on 2019-04-18 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20190413_1516'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stock',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='dop_money',
            name='dop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Dop_types', verbose_name='Тип расхода'),
        ),
        migrations.AlterField(
            model_name='dop_money',
            name='nak_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Purchase', verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingr', to='roles.Products', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='product',
            field=models.ForeignKey(limit_choices_to={'prigot': True}, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='roles.Products', verbose_name='Заготовляемый товар'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='products',
            name='edizm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Units', verbose_name='Ед.измерения'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Pizzerias', verbose_name='Пиццерия'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='spis',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Receivers', verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ostat',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Осталось на складе'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shtrih',
            field=models.CharField(editable=False, max_length=50, verbose_name='Штрих-код'),
        ),
    ]
