# Generated by Django 2.1.3 on 2019-03-02 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20190302_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Завсклад'), (2, 'Кассир'), (3, 'Закупщик'), (4, 'Заготовщик'), (5, 'Пиццемейкер'), (6, 'Пиццедоставщик'), (7, 'Пиццекассир')], null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
