# Generated by Django 2.2 on 2019-05-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20190501_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='kolvo',
            field=models.FloatField(default=0.0, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Товар'),
        ),
    ]
