# Generated by Django 2.2 on 2019-05-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20190501_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='artikul',
            field=models.CharField(default='', editable=False, max_length=6, verbose_name='Артикул'),
        ),
    ]
