# Generated by Django 2.2 on 2019-05-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_products_artikul'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Codes',
        ),
    ]
