# Generated by Django 2.2 on 2019-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_auto_20190418_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='maks_zakup',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='min_zakup',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='rashod',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='scena',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shtrih',
        ),
        migrations.AddField(
            model_name='products',
            name='maks_zakup',
            field=models.IntegerField(default=1, verbose_name='Закупка на дни'),
        ),
        migrations.AddField(
            model_name='products',
            name='min_zakup',
            field=models.IntegerField(default=1, verbose_name='Миним.дни для закупки'),
        ),
        migrations.AddField(
            model_name='products',
            name='rashod',
            field=models.IntegerField(default=1, verbose_name='Ср.расход в день'),
        ),
        migrations.AddField(
            model_name='products',
            name='scena',
            field=models.FloatField(default=1, verbose_name='Ср.цена'),
        ),
    ]
