# Generated by Django 2.2 on 2019-05-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_auto_20190501_0904'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='purchase',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='min_srok',
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='name',
            field=models.ForeignKey(limit_choices_to={'prigot': True}, on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='products',
            name='artikul',
            field=models.CharField(default='', editable=False, max_length=6, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='fact_kol',
            field=models.FloatField(default=0.0, verbose_name='Фактическое кол-во'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Накладная принята?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Поступил на склад?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='new_cost',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_kol',
            field=models.FloatField(default=0.0, verbose_name='Купленное кол-во'),
        ),
    ]
