# Generated by Django 2.1.3 on 2019-03-02 11:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_auto_20190302_1144'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pizzerias',
            managers=[
                ('pr', django.db.models.manager.Manager()),
            ],
        ),
    ]
