# Generated by Django 2.2 on 2019-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_auto_20190420_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rashod',
            field=models.FloatField(default=1, verbose_name='Ср.расход в день'),
        ),
    ]
