# Generated by Django 2.2 on 2019-05-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastCost',
        ),
    ]
