# Generated by Django 2.1.3 on 2019-03-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_auto_20190302_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='place',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='roles.Pizzerias', verbose_name='Пиццерия'),
        ),
    ]
