# Generated by Django 2.2 on 2019-05-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_delete_lastcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0, verbose_name='Последняя цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Продукт')),
            ],
        ),
    ]
