# Generated by Django 2.2 on 2019-05-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_auto_20190501_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='min_srok',
            field=models.DateField(null=True, verbose_name='Мин.срок годности'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='srok',
            field=models.DateField(null=True, verbose_name='Cрок годности'),
        ),
        migrations.CreateModel(
            name='LastCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0, verbose_name='Последняя цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Продукт')),
            ],
        ),
    ]
