# Generated by Django 2.2 on 2019-05-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_lastcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='min_srok',
        ),
    ]
