# Generated by Django 2.1.3 on 2019-03-05 14:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_auto_20190302_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('imag1', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edizm', models.CharField(max_length=20, verbose_name='Обозначение')),
                ('opis', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            managers=[
                ('unit', django.db.models.manager.Manager()),
            ],
        ),
    ]
