# Generated by Django 2.1.3 on 2019-03-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0009_products_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='imag1',
        ),
        migrations.AddField(
            model_name='products',
            name='artikul',
            field=models.CharField(default='', max_length=6, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='prigot',
            field=models.BooleanField(default=False, verbose_name='Приготавливаемый товар?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
