# Generated by Django 2.2 on 2019-05-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0009_purchase_min_srok'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='shtrih',
        ),
        migrations.CreateModel(
            name='Rashod_zagot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol', models.IntegerField(verbose_name='Кол-во')),
                ('nak_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Nakl_for_zagot', verbose_name='ID накладной')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Расходы заготовщика',
                'verbose_name_plural': 'Расходы заготовщика',
            },
        ),
    ]
