# Generated by Django 2.1.3 on 2019-03-09 04:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0011_products_edizm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postavsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(default='', max_length=50, verbose_name='Фирма-поставщик')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Контактное лицо')),
                ('contact', models.CharField(default='', max_length=50, verbose_name='Контактные данные')),
                ('place', models.TextField(default='', verbose_name='Расположение')),
            ],
            managers=[
                ('pos', django.db.models.manager.Manager()),
            ],
        ),
    ]
