# Generated by Django 2.2 on 2019-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0011_remove_purchase_min_srok'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='min_srok',
            field=models.DateField(null=True, verbose_name='Мин.срок годности'),
        ),
    ]
