# Generated by Django 2.1.3 on 2019-03-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0012_postavsh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postavsh',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
