# Generated by Django 2.1.3 on 2019-03-09 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0013_auto_20190309_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.IntegerField(verbose_name='Кол-во')),
                ('scena', models.IntegerField(default=1, verbose_name='Ср.цена')),
                ('rashod', models.IntegerField(default=1, verbose_name='Ср.расход в день')),
                ('maks_zakup', models.IntegerField(default=1, verbose_name='Закупка на дни')),
                ('min_zakup', models.IntegerField(default=1, verbose_name='Миним.дни для закупки')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.Products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
            managers=[
                ('st', django.db.models.manager.Manager()),
            ],
        ),
    ]
