# Generated by Django 2.2 on 2019-05-11 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0013_purchase_is_accepted_zakup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakupshiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(limit_choices_to={'prigot': True}, on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Продукт')),
                ('user', models.OneToOneField(limit_choices_to={'user__roles': 3}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
        ),
    ]
