# Generated by Django 2.2 on 2019-05-11 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0014_zakupshiki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nakl_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.FloatField(verbose_name='Сколько')),
                ('name', models.ForeignKey(limit_choices_to={'roles__role': 3}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
        ),
        migrations.DeleteModel(
            name='A',
        ),
        migrations.AlterModelOptions(
            name='zakupshiki',
            options={'verbose_name': 'Закупщик', 'verbose_name_plural': 'Закупщики'},
        ),
        migrations.AlterModelManagers(
            name='roles',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='zakupshiki',
            name='user',
            field=models.ForeignKey(limit_choices_to={'roles__role': 3}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
