# Generated by Django 2.1.3 on 2019-03-09 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0014_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': ' На склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.AlterField(
            model_name='products',
            name='edizm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.Units', verbose_name='Ед.измерения'),
        ),
    ]
