# Generated by Django 2.1.7 on 2019-03-19 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0015_auto_20190309_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dop_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Дополнительные расходы',
                'verbose_name_plural': 'Дополнительные расходы',
            },
        ),
        migrations.CreateModel(
            name='Dop_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название прочего расхода')),
                ('min_summ', models.IntegerField(verbose_name='Минимальная сумма')),
                ('max_summ', models.IntegerField(verbose_name='Максимальная сумма')),
            ],
            options={
                'verbose_name': 'Тип дополнительных расходов',
                'verbose_name_plural': 'Типы дополнительных расходов',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.IntegerField(verbose_name='Кол-во на 1 удиницу товара')),
                ('ingr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingr', to='roles.Products', verbose_name='Ингридиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='roles.Products', verbose_name='Заготовляемый товар')),
            ],
            options={
                'verbose_name': 'Ингридиент для приготовляемых товаров',
                'verbose_name_plural': 'Ингридиенты для приготовляемых товаров',
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nak_id', models.CharField(max_length=37, verbose_name='№ накладной')),
                ('dat', models.DateField(auto_now=True, verbose_name='Дата накладной')),
                ('nsumma', models.IntegerField(verbose_name='Требуемая сумма для закупки')),
                ('dsumma', models.IntegerField(verbose_name='Выданная сумма')),
                ('isumma', models.IntegerField(verbose_name='Истраченная сумма')),
                ('psumma', models.IntegerField(verbose_name='Прочие расходы')),
                ('rsumma', models.IntegerField(verbose_name='Итого расход')),
                ('vsumma', models.IntegerField(verbose_name='Сумма возврата/выдачи')),
                ('is_calculated', models.BooleanField(verbose_name='Расчет произведен?')),
            ],
            options={
                'verbose_name': 'Деньги для закупки',
                'verbose_name_plural': 'Деньги для закупки',
            },
        ),
        migrations.CreateModel(
            name='Nakl_for_zagot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkolvo', models.FloatField(verbose_name='Требуемое количество')),
                ('is_accepted', models.BooleanField(verbose_name='Накладная принята?')),
                ('pkolvo', models.FloatField(verbose_name='Приготовленное количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('is_maked', models.BooleanField(verbose_name='Товар приготовлен?')),
                ('ac_kolvo', models.FloatField(verbose_name='Принятое количество')),
                ('srok', models.DateField(verbose_name='Срок годности')),
                ('shtrih', models.IntegerField(verbose_name='Штрих-код')),
                ('in_stock', models.BooleanField(verbose_name='Поступил на склад?')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roles.Products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Накладная для заготовщика',
                'verbose_name_plural': 'Накладные для заготовщика',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nak_id', models.CharField(max_length=50, verbose_name='Номер накладной')),
                ('last_cost', models.FloatField(verbose_name='Последняя цена')),
                ('kolvo', models.FloatField(verbose_name='Требуемое кол-во')),
                ('min_srok', models.IntegerField(verbose_name='Мин.срок годности')),
                ('is_accepted', models.BooleanField(verbose_name='Накладная принята?')),
                ('purchased_kol', models.FloatField(verbose_name='Купленное кол-во')),
                ('new_cost', models.FloatField(verbose_name='Цена')),
                ('fact_kol', models.FloatField(verbose_name='Фактическое кол-во')),
                ('srok', models.DateField(verbose_name='Срок годности')),
                ('shtrih', models.IntegerField(verbose_name='Штрих-код')),
                ('is_delivered', models.BooleanField(verbose_name='Поступил на склад?')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roles.Products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Накладная для закупки',
                'verbose_name_plural': 'Накладная для закупки',
            },
            managers=[
                ('pur', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='ostat',
            field=models.FloatField(default=0.0, verbose_name='Осталось на складе'),
        ),
        migrations.AddField(
            model_name='stock',
            name='summ',
            field=models.FloatField(default=0.0, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='dop_money',
            name='dop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.Dop_types', verbose_name='Тип расхода'),
        ),
        migrations.AddField(
            model_name='dop_money',
            name='nak_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.Purchase', verbose_name='Номер накладной'),
        ),
    ]
