# Generated by Django 2.1.7 on 2019-03-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0016_auto_20190319_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='summ',
            field=models.FloatField(default=0.0, verbose_name='Сумма'),
        ),
    ]
