# Generated by Django 2.2 on 2019-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0018_auto_20190528_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='nak_id',
            field=models.IntegerField(default=0, verbose_name='Номер накладной'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='ac_kolvo',
            field=models.FloatField(default=0.0, verbose_name='Принятое количество'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='Поступил на склад?'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Накладная принята?'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='is_maked',
            field=models.BooleanField(default=False, verbose_name='Товар приготовлен?'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='pkolvo',
            field=models.FloatField(default=0.0, verbose_name='Приготовленное количество'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='srok',
            field=models.DateField(blank=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='tkolvo',
            field=models.FloatField(default=0.0, verbose_name='Требуемое количество'),
        ),
    ]
