# Generated by Django 2.2 on 2019-06-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0019_auto_20190604_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingr', to='roles.Products', verbose_name='Ингридиент'),
        ),
    ]
