# Generated by Django 2.2 on 2019-06-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0020_auto_20190604_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nakl_money',
        ),
    ]
