# Generated by Django 2.2 on 2019-06-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0022_money_receivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nakl_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.FloatField(verbose_name='Сколько')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Money_receivers', verbose_name='Кому')),
            ],
        ),
    ]
