# Generated by Django 2.2 on 2019-06-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0023_nakl_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='kolvo',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='name',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Товар'),
        ),
    ]
