# Generated by Django 2.2 on 2019-06-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0024_auto_20190606_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='kolvo',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='summ',
        ),
    ]
