# Generated by Django 2.2 on 2019-06-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0025_auto_20190613_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='shtrih',
            field=models.CharField(default='-----', max_length=20, verbose_name='Штрих-код'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='user',
            field=models.CharField(default='-----', max_length=20, verbose_name='Заготовщик'),
            preserve_default=False,
        ),
    ]
