# Generated by Django 2.2 on 2019-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0026_auto_20190615_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spis',
            name='kol',
            field=models.FloatField(verbose_name='Сколько'),
        ),
    ]
