# Generated by Django 2.2 on 2019-06-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0027_auto_20190615_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients_dop_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srok', models.FloatField(default=0.0, verbose_name='Срок хранения (часы)')),
                ('procent', models.FloatField(default=0.0, verbose_name='Погрешность (%)')),
                ('product', models.ForeignKey(limit_choices_to={'prigot': True}, on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Заготовляемый товар')),
            ],
        ),
    ]
