# Generated by Django 2.2 on 2019-06-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0028_ingredients_dop_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients_dop_info',
            name='product',
            field=models.OneToOneField(limit_choices_to={'prigot': True}, on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Заготовляемый товар'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='srok',
            field=models.DateTimeField(blank=True, verbose_name='Срок годности'),
        ),
    ]
