# Generated by Django 2.2 on 2019-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0031_purchase_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Возвращен?'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Возвращен?'),
        ),
    ]
