# Generated by Django 2.2 on 2019-07-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0035_auto_20190702_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spis',
            name='nak_id',
        ),
    ]
