# Generated by Django 2.2 on 2019-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0036_remove_spis_nak_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spis',
            name='nak_id',
            field=models.IntegerField(default=4, verbose_name='ID накладной'),
        ),
    ]
