# Generated by Django 2.2 on 2019-07-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0041_spis_nak_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spis',
        ),
    ]
