# Generated by Django 2.2 on 2019-07-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0042_delete_spis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spis',
            fields=[
                ('i', models.AutoField(primary_key=True, serialize=False)),
                ('nak_id', models.IntegerField(default=4, verbose_name='ID накладной')),
                ('user', models.CharField(max_length=20, verbose_name='Кто')),
                ('product', models.CharField(max_length=100, verbose_name='Что')),
                ('kol', models.FloatField(verbose_name='Сколько')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Receivers', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Накладная на списание',
                'verbose_name_plural': 'Накладные на списание',
            },
        ),
    ]
