# Generated by Django 2.2 on 2019-07-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0043_spis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types_of_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50, verbose_name='Тип денег')),
            ],
            options={
                'verbose_name': 'Тип денег',
                'verbose_name_plural': 'Типы денег',
            },
        ),
        migrations.AlterModelOptions(
            name='money',
            options={'verbose_name': 'Деньги', 'verbose_name_plural': 'Деньги'},
        ),
        migrations.RemoveField(
            model_name='money',
            name='dat',
        ),
        migrations.RemoveField(
            model_name='money',
            name='dsumma',
        ),
        migrations.RemoveField(
            model_name='money',
            name='is_calculated',
        ),
        migrations.RemoveField(
            model_name='money',
            name='isumma',
        ),
        migrations.RemoveField(
            model_name='money',
            name='nak_id',
        ),
        migrations.RemoveField(
            model_name='money',
            name='nsumma',
        ),
        migrations.RemoveField(
            model_name='money',
            name='psumma',
        ),
        migrations.RemoveField(
            model_name='money',
            name='rsumma',
        ),
        migrations.RemoveField(
            model_name='money',
            name='vsumma',
        ),
        migrations.AddField(
            model_name='money',
            name='kolvo',
            field=models.FloatField(default=0.0, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='kolvo',
            field=models.FloatField(default=0.0, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='money',
            name='types',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Types_of_money', verbose_name='Тип денег'),
        ),
    ]
