# Generated by Django 2.2 on 2019-07-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0044_auto_20190707_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='money',
            options={'verbose_name': 'Деньги для закупки', 'verbose_name_plural': 'Деньги для закупки'},
        ),
        migrations.RemoveField(
            model_name='money',
            name='kolvo',
        ),
        migrations.RemoveField(
            model_name='money',
            name='types',
        ),
        migrations.AddField(
            model_name='money',
            name='dat',
            field=models.DateField(auto_now=True, verbose_name='Дата накладной'),
        ),
        migrations.AddField(
            model_name='money',
            name='dsumma',
            field=models.IntegerField(default=0, verbose_name='Выданная сумма'),
        ),
        migrations.AddField(
            model_name='money',
            name='is_calculated',
            field=models.BooleanField(default=False, verbose_name='Расчет произведен?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='money',
            name='isumma',
            field=models.IntegerField(default=0, verbose_name='Истраченная сумма'),
        ),
        migrations.AddField(
            model_name='money',
            name='nak_id',
            field=models.CharField(default='0', max_length=37, verbose_name='№ накладной'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='money',
            name='nsumma',
            field=models.IntegerField(default=0, verbose_name='Требуемая сумма для закупки'),
        ),
        migrations.AddField(
            model_name='money',
            name='psumma',
            field=models.IntegerField(default=0, verbose_name='Прочие расходы'),
        ),
        migrations.AddField(
            model_name='money',
            name='rsumma',
            field=models.IntegerField(default=0, verbose_name='Итого расход'),
        ),
        migrations.AddField(
            model_name='money',
            name='vsumma',
            field=models.IntegerField(default=0, verbose_name='Сумма возврата/выдачи'),
        ),
        migrations.CreateModel(
            name='Moneys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.FloatField(default=0.0, verbose_name='Кол-во')),
                ('types', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Types_of_money', verbose_name='Тип денег')),
            ],
            options={
                'verbose_name': 'Деньги',
                'verbose_name_plural': 'Деньги',
            },
        ),
    ]
