# Generated by Django 2.2 on 2019-07-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0045_auto_20190707_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakl_money_zakup',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Types_of_money', verbose_name='Тип денег'),
        ),
        migrations.AlterField(
            model_name='types_of_money',
            name='types',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип денег'),
        ),
    ]
