# Generated by Django 2.2 on 2019-07-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0046_auto_20190707_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakl_money_other',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Types_of_money', verbose_name='Тип денег'),
        ),
    ]
