# Generated by Django 2.2 on 2019-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0049_auto_20190707_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='srok',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок годности'),
        ),
    ]
