# Generated by Django 2.2 on 2019-07-12 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0054_auto_20190712_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Товар'),
        ),
    ]
