# Generated by Django 2.2 on 2019-08-07 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0056_auto_20190722_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consuption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 7), null=True, verbose_name='Дата накладной'),
        ),
    ]
