# Generated by Django 2.2 on 2019-08-07 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0057_auto_20190807_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата накладной'),
        ),
    ]
