# Generated by Django 2.2 on 2019-08-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0060_auto_20190808_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
