# Generated by Django 2.2 on 2019-08-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0063_remove_products_artikul'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_ordered',
            field=models.BooleanField(default=False, editable=False, verbose_name='Заказан?'),
        ),
    ]
