# Generated by Django 2.2 on 2019-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0064_purchase_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Накладная принята?'),
        ),
    ]
