# Generated by Django 2.2 on 2019-08-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0065_auto_20190813_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='fact_kol',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактическое кол-во'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_accepted_zakup',
            field=models.BooleanField(default=False, verbose_name='Принято закупщиком?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Куплен?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Возвращен?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='new_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_kol',
            field=models.FloatField(default=0.0, verbose_name='Купленное кол-во'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='summ',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
