# Generated by Django 2.2 on 2019-08-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0066_auto_20190813_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='saler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Postavsh', verbose_name='Продавец'),
        ),
    ]
