# Generated by Django 2.2 on 2019-08-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0070_auto_20190822_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nakl_for_zagot',
            old_name='is_issued',
            new_name='is_given',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='fact_kol',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Фактическое кол-во'),
        ),
    ]
