# Generated by Django 2.2 on 2019-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0072_remove_nakl_for_zagot_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Ингридиенты приняты?'),
        ),
    ]
