# Generated by Django 2.2 on 2019-08-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0073_nakl_for_zagot_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients_dop_info',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products'),
        ),
        migrations.AlterField(
            model_name='moneys',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Types_of_money'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='zakupshiki',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Товар'),
        ),
    ]
