# Generated by Django 2.2 on 2019-08-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0074_auto_20190822_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='ac_kolvo',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='is_given',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='is_maked',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='is_taken',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='pkolvo',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='price',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='shtrih',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='srok',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='summ',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='tkolvo',
        ),
        migrations.RemoveField(
            model_name='nakl_for_zagot',
            name='user',
        ),
    ]
