# Generated by Django 2.2 on 2019-08-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0075_auto_20190822_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='ac_kolvo',
            field=models.FloatField(default=0.0, verbose_name='Принятое кол-во'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='Поступил на склад?'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Принята?'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='is_given',
            field=models.BooleanField(default=False, verbose_name='Ингридиенты выданы?'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='is_maked',
            field=models.BooleanField(default=False, verbose_name='Изготовлен?'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Возвращен?'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Ингридиенты приняты?'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='pkolvo',
            field=models.FloatField(default=0.0, verbose_name='Приготовленное кол-во'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='shtrih',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='srok',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='summ',
            field=models.FloatField(default=0.0, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='tkolvo',
            field=models.FloatField(default=0.0, verbose_name='Требуемое кол-во'),
        ),
        migrations.AddField(
            model_name='nakl_for_zagot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Zagot_types', verbose_name='Заготовщик'),
        ),
    ]
