# Generated by Django 2.2 on 2019-08-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0076_auto_20190822_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zagot_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nak_id', models.IntegerField()),
                ('kol', models.FloatField(verbose_name='Списанное кол-во')),
                ('kolvo', models.FloatField(verbose_name='Принятое кол-во')),
                ('status', models.BooleanField(verbose_name='Принято?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.Products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Zagot_types', verbose_name='Заготовщик')),
            ],
            options={
                'verbose_name': 'Списано закупщику',
                'verbose_name_plural': 'Списано закупщику',
            },
        ),
    ]
