# Generated by Django 2.2 on 2019-08-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0078_auto_20190827_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvester_Barcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nak_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('barcode', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
