# Generated by Django 2.2 on 2019-09-02 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0079_harvester_barcodes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneys',
            options={'verbose_name': 'Деньги', 'verbose_name_plural': 'Деньги'},
        ),
        migrations.AlterField(
            model_name='moneys',
            name='kolvo',
            field=models.FloatField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='moneys',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Types_of_money', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Buyer_Balans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField(verbose_name='Баланс')),
                ('debt', models.FloatField(verbose_name='Долг')),
                ('buyer', models.OneToOneField(limit_choices_to={'roles__role': 3}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Закупщик')),
            ],
            options={
                'verbose_name': 'Баланс закупщика',
                'verbose_name_plural': 'Баланс закупщиков',
            },
        ),
    ]
