# Generated by Django 2.2.5 on 2019-09-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0083_auto_20190905_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(verbose_name='Расход за сегодня')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='roles.Products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Дневной расход продукта',
                'verbose_name_plural': 'Дневной расход продуктов',
            },
        ),
    ]
