# Generated by Django 2.2.5 on 2019-09-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0084_daily_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_consumption',
            name='day',
            field=models.IntegerField(default=1, verbose_name='День'),
        ),
    ]
