# Generated by Django 2.2.5 on 2019-09-10 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0085_products_consumption_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester_barcodes',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='products_consumption',
            name='day',
            field=models.IntegerField(default=1, editable=False, verbose_name='День'),
        ),
    ]
