# Generated by Django 2.2.5 on 2019-10-17 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0089_nakl_for_zagot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester_stock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Заготовщик'),
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='shtrih',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
