# Generated by Django 2.2.5 on 2019-10-19 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0090_auto_20191017_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakupshiki',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.Products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='zakupshiki',
            name='user',
            field=models.ForeignKey(limit_choices_to={'roles__role': 3}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Закупщик'),
        ),
    ]
