# Generated by Django 2.2.5 on 2019-10-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0091_auto_20191019_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zagot_types',
            options={'verbose_name': 'Заготовщик', 'verbose_name_plural': 'Заготовщики'},
        ),
        migrations.AlterField(
            model_name='nakl_for_zagot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roles.Zagot_types', verbose_name='Заготовщик'),
        ),
    ]
