# Generated by Django 2.2.5 on 2019-10-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0093_auto_20191029_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spis',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
