# Generated by Django 2.2.5 on 2019-11-09 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0094_auto_20191030_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dopmoney',
            options={'verbose_name': 'Дополнительные расходы', 'verbose_name_plural': 'Дополнительные расходы'},
        ),
        migrations.AlterModelOptions(
            name='doptypes',
            options={'verbose_name': 'Тип доп.расходов', 'verbose_name_plural': 'Типы доп.расходов'},
        ),
        migrations.AddField(
            model_name='dopmoney',
            name='purchaser',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__role': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Закупщик'),
        ),
        migrations.AlterField(
            model_name='dopmoney',
            name='money',
            field=models.IntegerField(verbose_name='Потрачено'),
        ),
        migrations.AlterField(
            model_name='dopmoney',
            name='nak_id',
            field=models.IntegerField(verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='doptypes',
            name='max_summ',
            field=models.IntegerField(verbose_name='Максимальная сумма'),
        ),
        migrations.AlterField(
            model_name='doptypes',
            name='min_summ',
            field=models.IntegerField(verbose_name='Минимальная сумма'),
        ),
        migrations.AlterField(
            model_name='doptypes',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип расхода'),
        ),
    ]
