# Generated by Django 2.2.5 on 2019-12-14 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0095_auto_20191109_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_borrowed',
            field=models.BooleanField(default=False, verbose_name='Взят в долг?'),
        ),
        migrations.AlterField(
            model_name='dopmoney',
            name='dop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.DopTypes', verbose_name='Тип расхода'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Завсклад'), (2, 'Кассир'), (3, 'Закупщик'), (4, 'Заготовщик'), (5, 'Пиццемейкер'), (6, 'Пиццедоставщик'), (7, 'Пиццекассир'), (8, 'Администратор')], null=True, verbose_name='Роль'),
        ),
    ]
