# Generated by Django 2.2.5 on 2019-12-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0096_auto_20191214_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rediscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol', models.FloatField(default=0.0, verbose_name='Кол-во')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата переучета')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Переучет',
                'verbose_name_plural': 'Переучет',
            },
        ),
    ]
