# Generated by Django 2.2.5 on 2019-12-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0098_rediscount_red_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rediscount',
            name='date',
        ),
        migrations.CreateModel(
            name='Rediscount_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата переучета')),
                ('progress', models.FloatField(default=0.0, verbose_name='Прогресс переучета')),
                ('is_closed', models.FloatField(default=False, verbose_name='Закончен?')),
                ('rediscount', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.Rediscount', verbose_name='Переучет')),
            ],
            options={
                'verbose_name': 'Отчет о переучете',
                'verbose_name_plural': 'Отчеты о переучете',
            },
        ),
    ]
