# Generated by Django 2.2.5 on 2019-12-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0100_rediscount_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rediscount_info',
            name='progress',
            field=models.CharField(default=0.0, max_length=10, verbose_name='Прогресс переучета'),
        ),
    ]
