# Generated by Django 2.2.5 on 2019-12-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0101_auto_20191220_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='spis',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Отменена?'),
        ),
    ]
