# Generated by Django 2.2.5 on 2019-12-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0103_auto_20191220_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakl_money_other',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nakl_money_zakup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiving_money',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
