# Generated by Django 2.2.5 on 2019-12-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0104_auto_20191220_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcost',
            name='average',
            field=models.FloatField(default=0.0, verbose_name='Средняя цена'),
        ),
        migrations.AddField(
            model_name='lastcost',
            name='kol',
            field=models.FloatField(default=0.0, verbose_name='Купленное кол-во единиц'),
        ),
        migrations.AlterField(
            model_name='receiving_money',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
