# Generated by Django 2.2.5 on 2020-01-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0105_auto_20191220_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rediscount_info',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закончен?'),
        ),
    ]
