# Generated by Django 2.2.5 on 2020-01-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0106_auto_20200104_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='spis',
            name='product_name',
            field=models.CharField(default='', max_length=100, verbose_name='Название товара'),
            preserve_default=False,
        ),
    ]
