# Generated by Django 2.2.5 on 2020-01-19 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0107_spis_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Without_nakl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nak_id', models.IntegerField(verbose_name='Номер накладной')),
                ('srok', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('fact_kol', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Фактическое кол-во')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roles.Products', verbose_name='Название')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='От кого?')),
            ],
            options={
                'verbose_name': 'Без накладной',
                'verbose_name_plural': 'Без накладной',
            },
        ),
    ]
