# Generated by Django 2.2.5 on 2020-01-24 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0110_without_nakl_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
