# Generated by Django 2.2.5 on 2020-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0112_without_nakl_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='without_nakl',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Отправдено'),
        ),
    ]
